version: '3.8'

services:
  # API Gateway
  api_gateway:
    build:
      context: .
      dockerfile: Dockerfile
    command: python -m uvicorn api.api_gateway.main:app --host 0.0.0.0 --port 8000 --reload --reload-dir /app/api/api_gateway
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - AUTH_SERVICE_URL=http://auth_service:8001
      - PROJECT_SERVICE_URL=http://project_service:8002
      - DOCUMENT_SERVICE_URL=http://document_service:8003
      - NOTIFICATION_SERVICE_URL=http://notification_service:8004
      - EXTERNAL_TOOLS_SERVICE_URL=http://external_tools_service:8005
      - DATABASE_URL=postgresql://postgres:Adminqwert1234db@db.bhpkrxaqmlnyoxmcxxth.supabase.co:5432/postgres
      - JWT_ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
      - REFRESH_TOKEN_EXPIRE_DAYS=7
      - PYTHONPATH=/app
    depends_on:
      - auth_service
      - project_service
      - document_service
      - notification_service
      - external_tools_service
    networks:
      - taskhub-network
    restart: unless-stopped
    volumes:
      - ./api:/app/api

  # Auth Service
  auth_service:
    build:
      context: .
      dockerfile: Dockerfile
    command: python -m uvicorn api.auth_service.app.main:app --host 0.0.0.0 --port 8001 --reload --reload-dir /app/api/auth_service/app
    ports:
      - "8001:8001"
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgresql://postgres:Adminqwert1234db@db.bhpkrxaqmlnyoxmcxxth.supabase.co:5432/postgres
      - JWT_ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
      - REFRESH_TOKEN_EXPIRE_DAYS=7
      - PYTHONPATH=/app
    depends_on:
      - rabbitmq
    networks:
      - taskhub-network
    restart: unless-stopped
    volumes:
      - ./api:/app/api

  # Project Service
  project_service:
    build:
      context: .
      dockerfile: Dockerfile
    command: python -m uvicorn api.project_service.app.main:app --host 0.0.0.0 --port 8002 --reload --reload-dir /app/api/project_service/app
    ports:
      - "8002:8002"
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgresql://postgres:Adminqwert1234db@db.bhpkrxaqmlnyoxmcxxth.supabase.co:5432/postgres
      - JWT_ALGORITHM=HS256
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USER=guest
      - RABBITMQ_PASSWORD=guest
      - PYTHONPATH=/app
    depends_on:
      - rabbitmq
    networks:
      - taskhub-network
    restart: unless-stopped
    volumes:
      - ./api:/app/api

  # Document Service
  document_service:
    build:
      context: .
      dockerfile: Dockerfile
    command: python -m uvicorn api.document_service.app.main:app --host 0.0.0.0 --port 8003 --reload --reload-dir /app/api/document_service/app
    ports:
      - "8003:8003"
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgresql://postgres:Adminqwert1234db@db.bhpkrxaqmlnyoxmcxxth.supabase.co:5432/postgres
      - JWT_ALGORITHM=HS256
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USER=guest
      - RABBITMQ_PASSWORD=guest
      - PYTHONPATH=/app
    depends_on:
      - rabbitmq
    networks:
      - taskhub-network
    restart: unless-stopped
    volumes:
      - ./api:/app/api

  # Notification Service
  notification_service:
    build:
      context: .
      dockerfile: Dockerfile
    command: python -m uvicorn api.notification_service.app.main:app --host 0.0.0.0 --port 8004 --reload --reload-dir /app/api/notification_service/app
    ports:
      - "8004:8004"
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgresql://postgres:Adminqwert1234db@db.bhpkrxaqmlnyoxmcxxth.supabase.co:5432/postgres
      - JWT_ALGORITHM=HS256
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USER=guest
      - RABBITMQ_PASSWORD=guest
      - PYTHONPATH=/app
    depends_on:
      - rabbitmq
    networks:
      - taskhub-network
    restart: unless-stopped
    volumes:
      - ./api:/app/api

  # External Tools Service
  external_tools_service:
    build:
      context: .
      dockerfile: Dockerfile
    command: python -m uvicorn api.external_tools_service.app.main:app --host 0.0.0.0 --port 8005 --reload --reload-dir /app/api/external_tools_service/app
    ports:
      - "8005:8005"
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgresql://postgres:Adminqwert1234db@db.bhpkrxaqmlnyoxmcxxth.supabase.co:5432/postgres
      - JWT_ALGORITHM=HS256
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USER=guest
      - RABBITMQ_PASSWORD=guest
      - PYTHONPATH=/app
    depends_on:
      - rabbitmq
    networks:
      - taskhub-network
    restart: unless-stopped
    volumes:
      - ./api:/app/api

  # RabbitMQ
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - taskhub-network
    restart: unless-stopped

networks:
  taskhub-network:
    driver: bridge

volumes:
  rabbitmq_data: