version: '3.8'

services:
  # API Gateway
  api-gateway:
    build:
      context: .
      dockerfile: Dockerfile
    command: uvicorn api.api-gateway.main:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    environment:
      - AUTH_SERVICE_URL=http://auth-service:8001
      - PROJECT_SERVICE_URL=http://project-service:8002
      - DOCUMENT_SERVICE_URL=http://document-service:8003
      - NOTIFICATION_SERVICE_URL=http://notification-service:8004
      - EXTERNAL_TOOLS_SERVICE_URL=http://external-tools-service:8005
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/taskhub
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - JWT_ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
      - REFRESH_TOKEN_EXPIRE_DAYS=7
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_KEY=${SUPABASE_KEY}
    depends_on:
      - auth-service
      - project-service
      - document-service
      - notification-service
      - external-tools-service
    networks:
      - taskhub-network
    restart: always

  # Auth Service
  auth-service:
    build:
      context: .
      dockerfile: Dockerfile
    command: uvicorn api.auth-service.app.main:app --host 0.0.0.0 --port 8001
    ports:
      - "8001:8001"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/taskhub
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - JWT_ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
      - REFRESH_TOKEN_EXPIRE_DAYS=7
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_KEY=${SUPABASE_KEY}
    depends_on:
      - db
      - rabbitmq
    networks:
      - taskhub-network
    restart: always

  # Project Service
  project-service:
    build:
      context: .
      dockerfile: Dockerfile
    command: uvicorn api.project-service.app.main:app --host 0.0.0.0 --port 8002
    ports:
      - "8002:8002"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/taskhub
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - JWT_ALGORITHM=HS256
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USER=guest
      - RABBITMQ_PASSWORD=guest
    depends_on:
      - db
      - rabbitmq
    networks:
      - taskhub-network
    restart: always

  # Document Service
  document-service:
    build:
      context: .
      dockerfile: Dockerfile
    command: uvicorn api.document-service.app.main:app --host 0.0.0.0 --port 8003
    ports:
      - "8003:8003"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/taskhub
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - JWT_ALGORITHM=HS256
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_KEY=${SUPABASE_KEY}
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USER=guest
      - RABBITMQ_PASSWORD=guest
    depends_on:
      - db
      - rabbitmq
    networks:
      - taskhub-network
    restart: always

  # Notification Service
  notification-service:
    build:
      context: .
      dockerfile: Dockerfile
    command: uvicorn api.notification-service.app.main:app --host 0.0.0.0 --port 8004
    ports:
      - "8004:8004"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/taskhub
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - JWT_ALGORITHM=HS256
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USER=guest
      - RABBITMQ_PASSWORD=guest
      - EMAIL_HOST=${EMAIL_HOST}
      - EMAIL_PORT=${EMAIL_PORT}
      - EMAIL_USER=${EMAIL_USER}
      - EMAIL_PASSWORD=${EMAIL_PASSWORD}
      - EMAIL_FROM=${EMAIL_FROM}
      - PUSH_API_KEY=${PUSH_API_KEY}
      - PUSH_API_URL=${PUSH_API_URL}
      - SMS_API_KEY=${SMS_API_KEY}
      - SMS_API_URL=${SMS_API_URL}
    depends_on:
      - db
      - rabbitmq
    networks:
      - taskhub-network
    restart: always

  # External Tools Service
  external-tools-service:
    build:
      context: .
      dockerfile: Dockerfile
    command: uvicorn api.external-tools-service.app.main:app --host 0.0.0.0 --port 8005
    ports:
      - "8005:8005"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/taskhub
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - JWT_ALGORITHM=HS256
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USER=guest
      - RABBITMQ_PASSWORD=guest
    depends_on:
      - db
      - rabbitmq
    networks:
      - taskhub-network
    restart: always

  # Database
  db:
    image: postgres:16
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=taskhub
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - taskhub-network
    restart: always

  # RabbitMQ
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - taskhub-network
    restart: always

networks:
  taskhub-network:
    driver: bridge

volumes:
  postgres_data:
  rabbitmq_data: